/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Checking;

/**
 *
 * @author adity
 */
public class CreateChecking extends javax.swing.JPanel {

    /**
     * Creates new form createChecking
     */
    Checking checking;
    public CreateChecking(Checking checking) {
        initComponents();
        this.checking = checking;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCheckingAccountType = new javax.swing.JLabel();
        txtCheckingBankName = new javax.swing.JTextField();
        lblCheckingRoutingNumber = new javax.swing.JLabel();
        txtCheckingRoutingNumber = new javax.swing.JTextField();
        txtCheckingAccountBalance = new javax.swing.JTextField();
        txtCheckingAccountNumber = new javax.swing.JTextField();
        lblCheckingBankName = new javax.swing.JLabel();
        lblCheckingAccountNumber = new javax.swing.JLabel();
        lblCheckingInfo = new javax.swing.JLabel();
        lblCheckingAccountBalance = new javax.swing.JLabel();
        txtCheckingAccountType = new javax.swing.JTextField();
        btnSaveChecking = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCheckingAccountType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheckingAccountType.setText("Account Type:");
        add(lblCheckingAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 199, 128, 22));

        txtCheckingBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckingBankNameActionPerformed(evt);
            }
        });
        add(txtCheckingBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));

        lblCheckingRoutingNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheckingRoutingNumber.setText("Bank Routing Number:");
        add(lblCheckingRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));
        add(txtCheckingRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));
        add(txtCheckingAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));
        add(txtCheckingAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        lblCheckingBankName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheckingBankName.setText("Bank Name:");
        add(lblCheckingBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblCheckingAccountNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheckingAccountNumber.setText("Bank Account Number:");
        add(lblCheckingAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblCheckingInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCheckingInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCheckingInfo.setText("Checking Account Information");
        add(lblCheckingInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 27));

        lblCheckingAccountBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCheckingAccountBalance.setText("Account Balance:");
        add(lblCheckingAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));

        txtCheckingAccountType.setText("Checking");
        txtCheckingAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckingAccountTypeActionPerformed(evt);
            }
        });
        add(txtCheckingAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 201, 158, -1));

        btnSaveChecking.setText("Save");
        btnSaveChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCheckingActionPerformed(evt);
            }
        });
        add(btnSaveChecking, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 239, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCheckingActionPerformed
        // TODO add your handling code here:
        checking.setCheckingBankName(txtCheckingBankName.getText());
        checking.setCheckingRoutingNumber(txtCheckingRoutingNumber.getText());
        checking.setCheckingAccountBalance(txtCheckingAccountBalance.getText());
        checking.setCheckingAccountNumber(txtCheckingAccountNumber.getText());
        checking.setCheckingAccountType(txtCheckingAccountType.getText());
        
        JOptionPane.showMessageDialog(this, "Checking Account Information Saved");
    }//GEN-LAST:event_btnSaveCheckingActionPerformed

    private void txtCheckingBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckingBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckingBankNameActionPerformed

    private void txtCheckingAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckingAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckingAccountTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveChecking;
    private javax.swing.JLabel lblCheckingAccountBalance;
    private javax.swing.JLabel lblCheckingAccountNumber;
    private javax.swing.JLabel lblCheckingAccountType;
    private javax.swing.JLabel lblCheckingBankName;
    private javax.swing.JLabel lblCheckingInfo;
    private javax.swing.JLabel lblCheckingRoutingNumber;
    private javax.swing.JTextField txtCheckingAccountBalance;
    private javax.swing.JTextField txtCheckingAccountNumber;
    private javax.swing.JTextField txtCheckingAccountType;
    private javax.swing.JTextField txtCheckingBankName;
    private javax.swing.JTextField txtCheckingRoutingNumber;
    // End of variables declaration//GEN-END:variables
}
