/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.DriverLic;

/**
 *
 * @author adity
 */
public class CreateDriverLic extends javax.swing.JPanel {

    /**
     * Creates new form createDriverLic
     */
    DriverLic driverLic;
    public CreateDriverLic(DriverLic driverLic) {
        initComponents();
        this.driverLic = driverLic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLicenseNumber = new javax.swing.JLabel();
        lblexpirationDate = new javax.swing.JLabel();
        lblDriverInfo = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenceNumber = new javax.swing.JTextField();
        lblIssueDate = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        btnSaveDriverLic = new javax.swing.JButton();
        lblUploadPicture = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLicenseNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLicenseNumber.setText("License Number:");
        add(lblLicenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblexpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblexpirationDate.setText("Date of Expiration:");
        add(lblexpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblDriverInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDriverInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriverInfo.setText("Driver License Information");
        add(lblDriverInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 27));

        lblBloodType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBloodType.setText("Blood Type:");
        add(lblBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));
        add(txtLicenceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));

        lblIssueDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIssueDate.setText("Date of Issue:");
        add(lblIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));

        txtIssueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssueDateActionPerformed(evt);
            }
        });
        add(txtIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));
        add(txtBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));
        add(txtExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        btnSaveDriverLic.setText("Save");
        btnSaveDriverLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDriverLicActionPerformed(evt);
            }
        });
        add(btnSaveDriverLic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        lblUploadPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUploadPicture.setText("Upload Image");
        lblUploadPicture.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        lblUploadPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUploadPictureMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUploadPictureMousePressed(evt);
            }
        });
        add(lblUploadPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIssueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssueDateActionPerformed

    private void btnSaveDriverLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDriverLicActionPerformed
   // TODO add your handling code here:
   driverLic.setLicenceNumber(txtLicenceNumber.getText());
   driverLic.setBloodType(txtBloodType.getText());
   driverLic.setExpirationDate(txtExpirationDate.getText());
   driverLic.setIssueDate(txtIssueDate.getText());
   JOptionPane.showMessageDialog(this, "Driver License Information Saved");
    }//GEN-LAST:event_btnSaveDriverLicActionPerformed

    private void lblUploadPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUploadPictureMouseClicked
        // TODO add your handling code here:
        JFileChooser image = new JFileChooser();
        image.showOpenDialog(null);
        File pic = image.getSelectedFile();
        String path = pic.getAbsolutePath();
        ImageIcon driverImg = new ImageIcon(path);
        lblUploadPicture.setIcon(driverImg);
        driverLic.setFilePath(path);
    }//GEN-LAST:event_lblUploadPictureMouseClicked

    private void lblUploadPictureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUploadPictureMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUploadPictureMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDriverLic;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblDriverInfo;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblUploadPicture;
    private javax.swing.JLabel lblexpirationDate;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLicenceNumber;
    // End of variables declaration//GEN-END:variables
}
