/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Address;

/**
 *
 * @author adity
 */
public class CreateAddress extends javax.swing.JPanel {

    /**
     * Creates new form createAddress
     */
    Address address;
    public CreateAddress(Address address) {
        initComponents();
        this.address = address;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        lblCity = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        lblAddressInfo = new javax.swing.JLabel();
        btnSaveAddress = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));

        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));

        lblState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblState.setText("State:");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblZip.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZip.setText("Zip Code:");
        add(lblZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));
        add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        lblStreet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreet.setText("Street Address:");
        add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblAddressInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddressInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressInfo.setText("Address Information");
        add(lblAddressInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 27));

        btnSaveAddress.setText("Save");
        btnSaveAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddressActionPerformed(evt);
            }
        });
        add(btnSaveAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddressActionPerformed
        // TODO add your handling code here:
        address.setStreet(txtStreet.getText());
        address.setCity(txtCity.getText());
        address.setState(txtState.getText());
        address.setZip(txtZip.getText());
        
        JOptionPane.showMessageDialog(this, "Address Information Saved");
    }//GEN-LAST:event_btnSaveAddressActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveAddress;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblAddressInfo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
