/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Medical;

/**
 *
 * @author adity
 */
public class CreateMedical extends javax.swing.JPanel {

    /**
     * Creates new form createMedical
     */
    Medical medical;
    public CreateMedical(Medical medical) {
        initComponents();
        this.medical = medical;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAllergy1 = new javax.swing.JTextField();
        txtAllergy3 = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblAllergy2 = new javax.swing.JLabel();
        lblMedicalInfo = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();
        txtMedicalNumber = new javax.swing.JTextField();
        lblAllergy1 = new javax.swing.JLabel();
        btnSaveMedical = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));
        add(txtAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));
        add(txtAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        lblMedicalRecordNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedicalRecordNumber.setText(" Record Number:");
        add(lblMedicalRecordNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblAllergy2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAllergy2.setText("Allergy 2:");
        add(lblAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblMedicalInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMedicalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalInfo.setText(" Medical Record");
        add(lblMedicalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 27));

        lblAllergy3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAllergy3.setText("Allergy 3:");
        add(lblAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));
        add(txtMedicalNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));

        lblAllergy1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAllergy1.setText("Allergy 1:");
        add(lblAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));

        btnSaveMedical.setText("Save");
        btnSaveMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMedicalActionPerformed(evt);
            }
        });
        add(btnSaveMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMedicalActionPerformed
        // TODO add your handling code here:
        medical.setMedicalNumber(txtMedicalNumber.getText());
        medical.setAllergy1(txtAllergy1.getText());
        medical.setAllergy2(txtAllergy2.getText());
        medical.setAllergy3(txtAllergy3.getText());
        JOptionPane.showMessageDialog(this, "Medical Record Information Saved");
    }//GEN-LAST:event_btnSaveMedicalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveMedical;
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblMedicalInfo;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtMedicalNumber;
    // End of variables declaration//GEN-END:variables
}
