/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Address;
import model.Checking;
import model.Demographic;
import model.DriverLic;
import model.Medical;
import model.Saving;

/**
 *
 * @author adity
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Address address;
    Checking checking;
    Demographic demographic;
    DriverLic driverLic;
    Medical medical;
    Saving saving;
    public MainJFrame() {
        initComponents();
        address = new Address();
        checking = new Checking();
        demographic = new Demographic();
        driverLic = new DriverLic();
        medical = new Medical();
        saving = new Saving();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnViewDemographic = new javax.swing.JButton();
        btnCreateAddress = new javax.swing.JButton();
        btnViewAddress = new javax.swing.JButton();
        btnCreateChecking = new javax.swing.JButton();
        btnViewChecking = new javax.swing.JButton();
        btnCreateSaving = new javax.swing.JButton();
        btnViewSaving = new javax.swing.JButton();
        btnCreateDriverLic = new javax.swing.JButton();
        btnViewDriverLic = new javax.swing.JButton();
        btnCreateMedical = new javax.swing.JButton();
        btnViewMedical = new javax.swing.JButton();
        btnCreateDemographic = new javax.swing.JButton();
        lblDemoInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAddressInfo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblSavingInfo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblCheckingInfo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblDriverLicInfo = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblMedicalInfo = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblReportInfo = new javax.swing.JLabel();
        btnViewMedical1 = new javax.swing.JButton();
        btnViewMedical2 = new javax.swing.JButton();
        btnViewMedical3 = new javax.swing.JButton();
        btnViewRecord = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewDemographic.setBackground(new java.awt.Color(255, 255, 255));
        btnViewDemographic.setText("View");
        btnViewDemographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDemographicActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDemographic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 107, -1));

        btnCreateAddress.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAddress.setText("Create ");
        btnCreateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddressActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 109, -1));

        btnViewAddress.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAddress.setText("View");
        btnViewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddressActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, 109, -1));

        btnCreateChecking.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateChecking.setText("Create ");
        btnCreateChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCheckingActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateChecking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 397, 109, -1));

        btnViewChecking.setBackground(new java.awt.Color(255, 255, 255));
        btnViewChecking.setText("View ");
        btnViewChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheckingActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewChecking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 428, 109, -1));

        btnCreateSaving.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateSaving.setText("Create ");
        btnCreateSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSavingActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateSaving, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 109, -1));

        btnViewSaving.setBackground(new java.awt.Color(255, 255, 255));
        btnViewSaving.setText("View ");
        btnViewSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavingActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewSaving, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 311, 109, -1));

        btnCreateDriverLic.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateDriverLic.setText("Create  ");
        btnCreateDriverLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDriverLicActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateDriverLic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 518, 109, -1));

        btnViewDriverLic.setBackground(new java.awt.Color(255, 255, 255));
        btnViewDriverLic.setText("View");
        btnViewDriverLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDriverLicActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDriverLic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 549, 109, -1));

        btnCreateMedical.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateMedical.setText("Create");
        btnCreateMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedicalActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 639, 109, -1));

        btnViewMedical.setBackground(new java.awt.Color(255, 255, 255));
        btnViewMedical.setText("View");
        btnViewMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 109, -1));

        btnCreateDemographic.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateDemographic.setText("Create");
        btnCreateDemographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDemographicActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateDemographic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 107, -1));

        lblDemoInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDemoInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDemoInfo.setText("Demographic");
        jPanel1.add(lblDemoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 129, 21));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 129, 10));

        lblAddressInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddressInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressInfo.setText("Address");
        jPanel1.add(lblAddressInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 109, 21));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 233, 129, -1));

        lblSavingInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavingInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavingInfo.setText("Saving Account");
        jPanel1.add(lblSavingInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 109, 21));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 129, 10));

        lblCheckingInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCheckingInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCheckingInfo.setText("Checking Account");
        jPanel1.add(lblCheckingInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 109, 21));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 467, 129, 10));

        lblDriverLicInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDriverLicInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriverLicInfo.setText("Driver License");
        jPanel1.add(lblDriverLicInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 491, 109, 21));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 588, 129, 10));

        lblMedicalInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMedicalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalInfo.setText("Medical Record");
        jPanel1.add(lblMedicalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 608, 109, 21));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 709, 129, 10));

        lblReportInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReportInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportInfo.setText("Report");
        jPanel1.add(lblReportInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 729, 109, 21));

        btnViewMedical1.setBackground(new java.awt.Color(0, 0, 0));
        btnViewMedical1.setText("View");
        btnViewMedical1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedical1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewMedical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 109, -1));

        btnViewMedical2.setBackground(new java.awt.Color(0, 0, 0));
        btnViewMedical2.setText("View");
        btnViewMedical2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedical2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewMedical2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 109, -1));

        btnViewMedical3.setBackground(new java.awt.Color(0, 0, 0));
        btnViewMedical3.setText("View");
        btnViewMedical3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedical3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewMedical3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 109, -1));

        btnViewRecord.setBackground(new java.awt.Color(255, 255, 255));
        btnViewRecord.setText("View");
        btnViewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRecordActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 110, -1));

        jSplitPane2.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDemographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDemographicActionPerformed
        // TODO add your handling code here:
        CreateDemographic createDemographicPanel = new CreateDemographic(demographic);
        jSplitPane2.setRightComponent(createDemographicPanel);
    }//GEN-LAST:event_btnCreateDemographicActionPerformed

    private void btnViewDemographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDemographicActionPerformed
        // TODO add your handling code here:
        ViewDemographic viewDemographicPanel = new ViewDemographic(demographic);
        jSplitPane2.setRightComponent(viewDemographicPanel);
    }//GEN-LAST:event_btnViewDemographicActionPerformed

    private void btnCreateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddressActionPerformed
        // TODO add your handling code here:
        CreateAddress createAddressPanel = new CreateAddress(address);
        jSplitPane2.setRightComponent(createAddressPanel);
    }//GEN-LAST:event_btnCreateAddressActionPerformed

    private void btnViewAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddressActionPerformed
        // TODO add your handling code here:
        ViewAddress viewAddressPanel = new ViewAddress(address);
        jSplitPane2.setRightComponent(viewAddressPanel);
    }//GEN-LAST:event_btnViewAddressActionPerformed

    private void btnCreateCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCheckingActionPerformed
        // TODO add your handling code here:
        CreateChecking createCheckingPanel = new CreateChecking(checking);
        jSplitPane2.setRightComponent(createCheckingPanel);
    }//GEN-LAST:event_btnCreateCheckingActionPerformed

    private void btnViewCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheckingActionPerformed
        // TODO add your handling code here:
        ViewChecking viewCheckingPanel = new ViewChecking(checking);
        jSplitPane2.setRightComponent(viewCheckingPanel);
    }//GEN-LAST:event_btnViewCheckingActionPerformed

    private void btnCreateSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSavingActionPerformed
        // TODO add your handling code here:
        CreateSaving createSavingPanel = new CreateSaving(saving);
        jSplitPane2.setRightComponent(createSavingPanel);
    }//GEN-LAST:event_btnCreateSavingActionPerformed

    private void btnViewSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavingActionPerformed
        // TODO add your handling code here:
        ViewSaving viewSavingPanel = new ViewSaving(saving);
        jSplitPane2.setRightComponent(viewSavingPanel);
    }//GEN-LAST:event_btnViewSavingActionPerformed

    private void btnCreateDriverLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDriverLicActionPerformed
        // TODO add your handling code here:
        CreateDriverLic createDriverLicPanel = new CreateDriverLic(driverLic);
        jSplitPane2.setRightComponent(createDriverLicPanel);
    }//GEN-LAST:event_btnCreateDriverLicActionPerformed

    private void btnViewDriverLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDriverLicActionPerformed
        // TODO add your handling code here:
        ViewDriverLic viewDriverLicPanel = new ViewDriverLic(driverLic);
        jSplitPane2.setRightComponent(viewDriverLicPanel);
    }//GEN-LAST:event_btnViewDriverLicActionPerformed

    private void btnCreateMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedicalActionPerformed
        // TODO add your handling code here:
        CreateMedical createMedicalPanel = new CreateMedical(medical);
        jSplitPane2.setRightComponent(createMedicalPanel);
    }//GEN-LAST:event_btnCreateMedicalActionPerformed

    private void btnViewMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalActionPerformed
        // TODO add your handling code here:
        ViewMedical viewMedicalPanel = new ViewMedical(medical);
        jSplitPane2.setRightComponent(viewMedicalPanel);
    }//GEN-LAST:event_btnViewMedicalActionPerformed

    private void btnViewMedical1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedical1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMedical1ActionPerformed

    private void btnViewMedical2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedical2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMedical2ActionPerformed

    private void btnViewMedical3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedical3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMedical3ActionPerformed

    private void btnViewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRecordActionPerformed
        // TODO add your handling code here:
        ViewReport viewReportPanel = new ViewReport(demographic,address,medical,driverLic,checking,saving);
        jSplitPane2.setRightComponent(viewReportPanel);
    }//GEN-LAST:event_btnViewRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAddress;
    private javax.swing.JButton btnCreateChecking;
    private javax.swing.JButton btnCreateDemographic;
    private javax.swing.JButton btnCreateDriverLic;
    private javax.swing.JButton btnCreateMedical;
    private javax.swing.JButton btnCreateSaving;
    private javax.swing.JButton btnViewAddress;
    private javax.swing.JButton btnViewChecking;
    private javax.swing.JButton btnViewDemographic;
    private javax.swing.JButton btnViewDriverLic;
    private javax.swing.JButton btnViewMedical;
    private javax.swing.JButton btnViewMedical1;
    private javax.swing.JButton btnViewMedical2;
    private javax.swing.JButton btnViewMedical3;
    private javax.swing.JButton btnViewRecord;
    private javax.swing.JButton btnViewSaving;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lblAddressInfo;
    private javax.swing.JLabel lblCheckingInfo;
    private javax.swing.JLabel lblDemoInfo;
    private javax.swing.JLabel lblDriverLicInfo;
    private javax.swing.JLabel lblMedicalInfo;
    private javax.swing.JLabel lblReportInfo;
    private javax.swing.JLabel lblSavingInfo;
    // End of variables declaration//GEN-END:variables
}
