/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Address;

/**
 *
 * @author adity
 */
public class ViewAddress extends javax.swing.JPanel {

    /**
     * Creates new form viewAddress
     */
    Address address;
    public ViewAddress(Address address) {
        initComponents();
        this.address = address;
        displayAddress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStreet = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblAddressInfo = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtStreet.setEditable(false);
        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });
        add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));

        txtCity.setEditable(false);
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));

        txtZip.setEditable(false);
        add(txtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));

        txtState.setEditable(false);
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        lblStreet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreet.setText("Street Address:");
        add(lblStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblState.setText("State:");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblAddressInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddressInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddressInfo.setText("View Address Information");
        add(lblAddressInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 27));

        lblZip.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZip.setText("Zip Code:");
        add(lblZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));
    }// </editor-fold>//GEN-END:initComponents

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAddressInfo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
    private void displayAddress(){
        txtStreet.setText(address.getStreet());
        txtCity.setText(address.getCity());
        txtState.setText(address.getState());
        txtZip.setText(address.getZip());
    }

}
