/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import model.DriverLic;

/**
 *
 * @author adity
 */
public class ViewDriverLic extends javax.swing.JPanel {

    /**
     * Creates new form viewDriverLic
     */
    DriverLic driverLic;
    public ViewDriverLic(DriverLic driverLic) {
        initComponents();
        this.driverLic = driverLic;
        displayDriverLic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        lblLicenseNumber = new javax.swing.JLabel();
        lblexpirationDate = new javax.swing.JLabel();
        lblDriverInfo = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        txtLicenceNumber = new javax.swing.JTextField();
        lblIssueDate = new javax.swing.JLabel();
        lblDriverPic = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIssueDate.setEditable(false);
        add(txtIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));

        txtBloodType.setEditable(false);
        add(txtBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));

        txtExpirationDate.setEditable(false);
        add(txtExpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        lblLicenseNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLicenseNumber.setText("License Number:");
        add(lblLicenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblexpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblexpirationDate.setText("Date of Expiration:");
        add(lblexpirationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblDriverInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDriverInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriverInfo.setText("View Driver License Information");
        add(lblDriverInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 27));

        lblBloodType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBloodType.setText("Blood Type:");
        add(lblBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));

        txtLicenceNumber.setEditable(false);
        add(txtLicenceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));

        lblIssueDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIssueDate.setText("Date of Issue:");
        add(lblIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));

        lblDriverPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDriverPic.setText("Image");
        lblDriverPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblDriverPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 203, 158, 57));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblDriverInfo;
    private javax.swing.JLabel lblDriverPic;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblexpirationDate;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtLicenceNumber;
    // End of variables declaration//GEN-END:variables
    private void displayDriverLic(){
        txtLicenceNumber.setText(driverLic.getLicenceNumber());
        txtIssueDate.setText(driverLic.getIssueDate());
        txtExpirationDate.setText(driverLic.getExpirationDate());
        txtBloodType.setText(driverLic.getBloodType());
        
        ImageIcon driverImg = new ImageIcon(driverLic.getFilePath());
        lblDriverPic.setIcon(driverImg);
    }
}
