/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Medical;

/**
 *
 * @author adity
 */
public class ViewMedical extends javax.swing.JPanel {

    /**
     * Creates new form viewMedical
     */
    Medical medical;
    public ViewMedical(Medical medical) {
        initComponents();
        this.medical = medical;
        displayMedical();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMedicalNumber = new javax.swing.JTextField();
        lblAllergy1 = new javax.swing.JLabel();
        txtAllergy1 = new javax.swing.JTextField();
        txtAllergy3 = new javax.swing.JTextField();
        txtAllergy2 = new javax.swing.JTextField();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblAllergy2 = new javax.swing.JLabel();
        lblMedicalInfo = new javax.swing.JLabel();
        lblAllergy3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMedicalNumber.setEditable(false);
        txtMedicalNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalNumberActionPerformed(evt);
            }
        });
        add(txtMedicalNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));

        lblAllergy1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAllergy1.setText("Allergy 1:");
        add(lblAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));

        txtAllergy1.setEditable(false);
        add(txtAllergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));

        txtAllergy3.setEditable(false);
        txtAllergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergy3ActionPerformed(evt);
            }
        });
        add(txtAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));

        txtAllergy2.setEditable(false);
        add(txtAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        lblMedicalRecordNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedicalRecordNumber.setText("Record Number:");
        add(lblMedicalRecordNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblAllergy2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAllergy2.setText("Allergy 2:");
        add(lblAllergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblMedicalInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMedicalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalInfo.setText(" View Medical Record");
        add(lblMedicalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 27));

        lblAllergy3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAllergy3.setText("Allergy 3:");
        add(lblAllergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicalNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalNumberActionPerformed

    private void txtAllergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergy3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAllergy1;
    private javax.swing.JLabel lblAllergy2;
    private javax.swing.JLabel lblAllergy3;
    private javax.swing.JLabel lblMedicalInfo;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JTextField txtAllergy1;
    private javax.swing.JTextField txtAllergy2;
    private javax.swing.JTextField txtAllergy3;
    private javax.swing.JTextField txtMedicalNumber;
    // End of variables declaration//GEN-END:variables
    private void displayMedical(){
        txtMedicalNumber.setText(medical.getMedicalNumber());
        txtAllergy1.setText(medical.getAllergy1());
        txtAllergy2.setText(medical.getAllergy2());
        txtAllergy3.setText(medical.getAllergy3());   
    }
}
