/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Saving;

/**
 *
 * @author adity
 */
public class ViewSaving extends javax.swing.JPanel {

    /**
     * Creates new form viewSaving
     */
    Saving saving;
    public ViewSaving(Saving saving) {
        initComponents();
        this.saving = saving;
        displaySaving();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSavingAccountNumber = new javax.swing.JTextField();
        lblSavingBankName = new javax.swing.JLabel();
        lblSavingAccountNumber = new javax.swing.JLabel();
        lblSavingInfo = new javax.swing.JLabel();
        lblSavingAccountBalance = new javax.swing.JLabel();
        txtSavingAccountType = new javax.swing.JTextField();
        lblSavingAccountType = new javax.swing.JLabel();
        txtSavingBankName = new javax.swing.JTextField();
        lblSavingRoutingNumber = new javax.swing.JLabel();
        txtSavingRoutingNumber = new javax.swing.JTextField();
        txtSavingAccountBalance = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSavingAccountNumber.setEditable(false);
        add(txtSavingAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 145, 158, -1));

        lblSavingBankName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSavingBankName.setText("Bank Name:");
        add(lblSavingBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 87, 128, 22));

        lblSavingAccountNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSavingAccountNumber.setText("Bank Account Number:");
        add(lblSavingAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, 128, 22));

        lblSavingInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSavingInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavingInfo.setText("View Saving Account Information");
        add(lblSavingInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 27));

        lblSavingAccountBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSavingAccountBalance.setText("Account Balance:");
        add(lblSavingAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 128, 22));

        txtSavingAccountType.setEditable(false);
        add(txtSavingAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 201, 158, -1));

        lblSavingAccountType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSavingAccountType.setText("Account Type:");
        add(lblSavingAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 199, 128, 22));

        txtSavingBankName.setEditable(false);
        add(txtSavingBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 89, 158, -1));

        lblSavingRoutingNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSavingRoutingNumber.setText("Bank Routing Number:");
        add(lblSavingRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 115, 128, 22));

        txtSavingRoutingNumber.setEditable(false);
        add(txtSavingRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 117, 158, -1));

        txtSavingAccountBalance.setEditable(false);
        txtSavingAccountBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavingAccountBalanceActionPerformed(evt);
            }
        });
        add(txtSavingAccountBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 173, 158, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSavingAccountBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavingAccountBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavingAccountBalanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSavingAccountBalance;
    private javax.swing.JLabel lblSavingAccountNumber;
    private javax.swing.JLabel lblSavingAccountType;
    private javax.swing.JLabel lblSavingBankName;
    private javax.swing.JLabel lblSavingInfo;
    private javax.swing.JLabel lblSavingRoutingNumber;
    private javax.swing.JTextField txtSavingAccountBalance;
    private javax.swing.JTextField txtSavingAccountNumber;
    private javax.swing.JTextField txtSavingAccountType;
    private javax.swing.JTextField txtSavingBankName;
    private javax.swing.JTextField txtSavingRoutingNumber;
    // End of variables declaration//GEN-END:variables
    private void displaySaving(){
        txtSavingAccountNumber.setText(saving.getSavingAccountNumber());
        txtSavingAccountBalance.setText(saving.getSavingAccountBalance());
        txtSavingRoutingNumber.setText(saving.getSavingRoutingNumber());
        txtSavingAccountType.setText(saving.getSavingAccountType());
        txtSavingBankName.setText(saving.getSavingBankName());
    }
}
