/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Dish;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adity
 */
public class ManageMenu extends javax.swing.JPanel {

    /**
     * Creates new form ManageMenu
     */
    private JPanel userContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    private Dish dish;
    public ManageMenu(JPanel userContainer,UserAccount userAccount,EcoSystem ecosystem) {
        initComponents();
        this.userContainer = userContainer;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        displayMenu();
    }
    
    public void displayMenu(){
        DefaultTableModel table = (DefaultTableModel) tblMenu.getModel();
        
        table.setRowCount(0);
        
       
        for (Restaurant restaurant:ecosystem.getRestaurantDirectory().getRestaurantDirectory()) {
           
            if (restaurant.getRestaurantUserName().equals(userAccount.getUsername())) {
                if(!(restaurant.getMenuList().isEmpty())){
                    for(Dish dish:restaurant.getMenuList()){
                    Object[] row = new Object[3];
                    row[0] = dish.getDishName();
                    row[1] = dish.getDishDescription();
                    row[2] = dish.getPrice();
                    table.addRow(row);
                    System.out.println("Exception 1");
               }
                }else{
                    System.out.println("Exception");
                }
               
                
            
            
        }
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerPassword = new javax.swing.JTextField();
        lblCustomerPassword = new javax.swing.JLabel();
        txtCustomerUserName = new javax.swing.JTextField();
        lblCustomerUserName = new javax.swing.JLabel();
        btnCustomerDelete = new javax.swing.JButton();
        btnCustomerCreate = new javax.swing.JButton();
        btnCustomerBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();

        setBackground(new java.awt.Color(214, 208, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerName.setText("Item Name :");
        add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 80, 20));
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 260, 30));

        txtCustomerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPasswordActionPerformed(evt);
            }
        });
        add(txtCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 260, 30));

        lblCustomerPassword.setText("Price :");
        add(lblCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 20));

        txtCustomerUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerUserNameActionPerformed(evt);
            }
        });
        add(txtCustomerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 260, 30));

        lblCustomerUserName.setText("Description :");
        add(lblCustomerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, 20));

        btnCustomerDelete.setBackground(new java.awt.Color(214, 50, 48));
        btnCustomerDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerDelete.setText("Delete");
        btnCustomerDelete.setBorder(null);
        btnCustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDeleteActionPerformed(evt);
            }
        });
        add(btnCustomerDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 120, 40));

        btnCustomerCreate.setBackground(new java.awt.Color(214, 50, 48));
        btnCustomerCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerCreate.setText("Add Item");
        btnCustomerCreate.setBorder(null);
        btnCustomerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerCreateActionPerformed(evt);
            }
        });
        add(btnCustomerCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 130, 40));

        btnCustomerBack.setBackground(new java.awt.Color(214, 50, 48));
        btnCustomerBack.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerBack.setText("Back");
        btnCustomerBack.setBorder(null);
        btnCustomerBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerBackActionPerformed(evt);
            }
        });
        add(btnCustomerBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 40));

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Description", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblMenu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 660, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPasswordActionPerformed

    private void txtCustomerUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerUserNameActionPerformed

    private void btnCustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDeleteActionPerformed
        // TODO add your handling code here:
         int focusRow = tblMenu.getSelectedRow();
        if(focusRow >= 0){
            int focusButton = JOptionPane.YES_NO_OPTION;
            int focusResult = JOptionPane.showConfirmDialog(null, "Confirm delete??","Warning",focusButton);
            if(focusResult == JOptionPane.YES_OPTION){
                
                for(Restaurant restaurant:ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
                    if(restaurant.getRestaurantUserName().equals(userAccount.getUsername())){
                        ecosystem.getRestaurantDirectory().removeMenu(restaurant, dish);
                        System.out.println("Exception 300");
                    }   
                }
                displayMenu();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a dish to proceed for deletion");
        }
    }//GEN-LAST:event_btnCustomerDeleteActionPerformed

    private void btnCustomerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerCreateActionPerformed
        // TODO add your handling code here:
        for(Restaurant restaurant : ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
            if(restaurant.getRestaurantUserName().equals(userAccount.getUsername())){
                dish = ecosystem.getRestaurantDirectory().addMenu(restaurant, txtCustomerName.getText(), txtCustomerUserName.getText(), txtCustomerPassword.getText());
                System.out.println("Exception 2");
            }
        }
        
        displayMenu();
    }//GEN-LAST:event_btnCustomerCreateActionPerformed

    private void btnCustomerBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerBackActionPerformed
        // TODO add your handling code here:
        userContainer.remove(this);
        CardLayout card = (CardLayout) userContainer.getLayout();
        card.previous(userContainer);
    }//GEN-LAST:event_btnCustomerBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerBack;
    private javax.swing.JButton btnCustomerCreate;
    private javax.swing.JButton btnCustomerDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerPassword;
    private javax.swing.JLabel lblCustomerUserName;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPassword;
    private javax.swing.JTextField txtCustomerUserName;
    // End of variables declaration//GEN-END:variables
}
