/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adity
 */
public class ManageRestaurant extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurant
     */
    private JPanel userContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    public ManageRestaurant(JPanel userContainer,EcoSystem ecosystem) {
        initComponents();
        this.ecosystem = ecosystem;
        this.userContainer = userContainer;
        displayRestaurantTable();
    }
    
    public void displayRestaurantTable(){
         DefaultTableModel table = (DefaultTableModel) tblRestaurant.getModel();
          table.setRowCount(0);
        for(UserAccount userAccount: ecosystem.getUserAccountDirectory().getUserAccountList()){
            
            if(userAccount.getRole().getClass().getName().equals("Business.Role.AdminRole")){
                Object [] row = new Object[3];
                row[0] = userAccount.getName();
                row[1] = userAccount.getUsername();
                row[2] = userAccount.getPassword();
                table.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerPassword = new javax.swing.JTextField();
        lblCustomerPassword = new javax.swing.JLabel();
        txtCustomerUserName = new javax.swing.JTextField();
        lblCustomerUserName = new javax.swing.JLabel();
        btnRestaurantSave = new javax.swing.JButton();
        btnRestaurantUpdate = new javax.swing.JButton();
        btnRestaurantDelete = new javax.swing.JButton();
        btnRestaurantCreate = new javax.swing.JButton();
        btnRestaurantBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurant = new javax.swing.JTable();

        setBackground(new java.awt.Color(214, 208, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerName.setText("Name :");
        add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 80, 20));
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 260, 30));

        txtCustomerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPasswordActionPerformed(evt);
            }
        });
        add(txtCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 260, 30));

        lblCustomerPassword.setText("User Password :");
        add(lblCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 80, 20));

        txtCustomerUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerUserNameActionPerformed(evt);
            }
        });
        add(txtCustomerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 260, 30));

        lblCustomerUserName.setText("User Name :");
        add(lblCustomerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 80, 20));

        btnRestaurantSave.setBackground(new java.awt.Color(214, 50, 48));
        btnRestaurantSave.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurantSave.setText("Save");
        btnRestaurantSave.setBorder(null);
        btnRestaurantSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantSaveActionPerformed(evt);
            }
        });
        add(btnRestaurantSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, 40));

        btnRestaurantUpdate.setBackground(new java.awt.Color(214, 50, 48));
        btnRestaurantUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurantUpdate.setText("Update");
        btnRestaurantUpdate.setBorder(null);
        btnRestaurantUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantUpdateActionPerformed(evt);
            }
        });
        add(btnRestaurantUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 120, 40));

        btnRestaurantDelete.setBackground(new java.awt.Color(214, 50, 48));
        btnRestaurantDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurantDelete.setText("Delete");
        btnRestaurantDelete.setBorder(null);
        btnRestaurantDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantDeleteActionPerformed(evt);
            }
        });
        add(btnRestaurantDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 120, 40));

        btnRestaurantCreate.setBackground(new java.awt.Color(214, 50, 48));
        btnRestaurantCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurantCreate.setText("Create");
        btnRestaurantCreate.setBorder(null);
        btnRestaurantCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantCreateActionPerformed(evt);
            }
        });
        add(btnRestaurantCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 170, 30));

        btnRestaurantBack.setBackground(new java.awt.Color(214, 50, 48));
        btnRestaurantBack.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurantBack.setText("Back");
        btnRestaurantBack.setBorder(null);
        btnRestaurantBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantBackActionPerformed(evt);
            }
        });
        add(btnRestaurantBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 40));

        tblRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Restaurant Name", "Restaurant User Name", "Restaurant Password"
            }
        ));
        jScrollPane1.setViewportView(tblRestaurant);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 660, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPasswordActionPerformed

    private void txtCustomerUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerUserNameActionPerformed

    private void btnRestaurantSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantSaveActionPerformed
        // TODO add your handling code here:
        if(txtCustomerName.getText().equals("") || txtCustomerUserName.getText().equals("") || txtCustomerPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter all fields");
        }else{
           ecosystem.getUserAccountDirectory().updateUserAccount(userAccount,txtCustomerName.getText(),txtCustomerUserName.getText(),txtCustomerPassword.getText(),null,null);
        displayRestaurantTable();
        txtCustomerName.setText("");
        txtCustomerUserName.setText("");
        txtCustomerPassword.setText("");
        } 
        
    }//GEN-LAST:event_btnRestaurantSaveActionPerformed

    private void btnRestaurantUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantUpdateActionPerformed
        // TODO add your handling code here:
        int focusRow = tblRestaurant.getSelectedRow();

        if(focusRow >= 0){
            String name = (String) tblRestaurant.getValueAt(focusRow, 0);
            String username= (String) tblRestaurant.getValueAt(focusRow, 1);
            String password= (String) tblRestaurant.getValueAt(focusRow, 2);
            userAccount = ecosystem.getUserAccountDirectory().authenticateUser(username, password);

            txtCustomerName.setText(name+"");
            txtCustomerUserName.setText(username+"");
            txtCustomerPassword.setText(password+"");

            JOptionPane.showMessageDialog(null,"Please press save button to save the restaurant information after updating the text field");

        }
        else {
            JOptionPane.showMessageDialog(null,"Please select a restaurant to update a profile");
        }
    }//GEN-LAST:event_btnRestaurantUpdateActionPerformed

    private void btnRestaurantDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantDeleteActionPerformed
        // TODO add your handling code here:
        int focusRow = tblRestaurant.getSelectedRow();
        if(focusRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Confirm delete?","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                String username= (String) tblRestaurant.getValueAt(focusRow, 1);
                String pwd= (String) tblRestaurant.getValueAt(focusRow, 2);
                UserAccount user=ecosystem.getUserAccountDirectory().authenticateUser(username, pwd);

               
                ecosystem.getUserAccountDirectory().deleteUserAccount(user);
                ecosystem.getRestaurantDirectory().deleteRestaurant(user.getUsername());
                displayRestaurantTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a restaurant to delete the account");
        }
    }//GEN-LAST:event_btnRestaurantDeleteActionPerformed

    private void btnRestaurantCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantCreateActionPerformed
        // TODO add your handling code here:
        if(txtCustomerName.getText().equals("") || txtCustomerUserName.getText().equals("") || txtCustomerPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter all fields");
        }else{
            if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtCustomerUserName.getText())){
            UserAccount userAcc = ecosystem.getUserAccountDirectory().createUserAccount(txtCustomerName.getText(),txtCustomerUserName.getText(),txtCustomerPassword.getText(),null,null,null ,new AdminRole());
            Restaurant restaurant = ecosystem.getRestaurantDirectory().createRestaurant(txtCustomerUserName.getText());
            displayRestaurantTable();
            System.out.println("1");
            txtCustomerName.setText("");
            txtCustomerUserName.setText("");
            txtCustomerPassword.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Restaurant Username is not unique");
        }
        } 
    }//GEN-LAST:event_btnRestaurantCreateActionPerformed

    private void btnRestaurantBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantBackActionPerformed
        // TODO add your handling code here:
        userContainer.remove(this);
        CardLayout card = (CardLayout) userContainer.getLayout();
        card.previous(userContainer);
    }//GEN-LAST:event_btnRestaurantBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestaurantBack;
    private javax.swing.JButton btnRestaurantCreate;
    private javax.swing.JButton btnRestaurantDelete;
    private javax.swing.JButton btnRestaurantSave;
    private javax.swing.JButton btnRestaurantUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerPassword;
    private javax.swing.JLabel lblCustomerUserName;
    private javax.swing.JTable tblRestaurant;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPassword;
    private javax.swing.JTextField txtCustomerUserName;
    // End of variables declaration//GEN-END:variables
}
