/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adity
 */
public class ManageDeliveryMan extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryMan
     */
    
    private JPanel userContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    public ManageDeliveryMan(JPanel userContainer,EcoSystem ecosystem) {
        initComponents();
        
        this.userContainer = userContainer;
        this.ecosystem = ecosystem;
        displayDeliveryTable();
    }
    
    
    public void displayDeliveryTable(){
        DefaultTableModel tablemodel = (DefaultTableModel) tblDelivery.getModel();
        
        tablemodel.setRowCount(0);
        for(UserAccount userAccount : ecosystem.getUserAccountDirectory().getUserAccountList()){
            if(userAccount.getRole().getClass().getName()=="Business.Role.DeliverManRole"){
                Object [] row = new Object[3];
                row[0] = userAccount.getName();
                row[1] = userAccount.getUsername();
                row[2] = userAccount.getPassword();
                
                tablemodel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerPassword = new javax.swing.JTextField();
        lblCustomerPassword = new javax.swing.JLabel();
        txtCustomerUserName = new javax.swing.JTextField();
        lblCustomerUserName = new javax.swing.JLabel();
        btnDeliverySave = new javax.swing.JButton();
        btnDeliveryUpdate = new javax.swing.JButton();
        btnDeliveryDelete = new javax.swing.JButton();
        btnDeliveryCreate = new javax.swing.JButton();
        btnDeliveryBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDelivery = new javax.swing.JTable();

        setBackground(new java.awt.Color(214, 208, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustomerName.setText("Name :");
        add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 80, 20));
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 260, 30));

        txtCustomerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPasswordActionPerformed(evt);
            }
        });
        add(txtCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 260, 30));

        lblCustomerPassword.setText("User Password :");
        add(lblCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 80, 20));

        txtCustomerUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerUserNameActionPerformed(evt);
            }
        });
        add(txtCustomerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 260, 30));

        lblCustomerUserName.setText("User Name :");
        add(lblCustomerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 20));

        btnDeliverySave.setBackground(new java.awt.Color(214, 50, 48));
        btnDeliverySave.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliverySave.setText("Save");
        btnDeliverySave.setBorder(null);
        btnDeliverySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliverySaveActionPerformed(evt);
            }
        });
        add(btnDeliverySave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 40));

        btnDeliveryUpdate.setBackground(new java.awt.Color(214, 50, 48));
        btnDeliveryUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliveryUpdate.setText("Update");
        btnDeliveryUpdate.setBorder(null);
        btnDeliveryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryUpdateActionPerformed(evt);
            }
        });
        add(btnDeliveryUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 120, 40));

        btnDeliveryDelete.setBackground(new java.awt.Color(214, 50, 48));
        btnDeliveryDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliveryDelete.setText("Delete");
        btnDeliveryDelete.setBorder(null);
        btnDeliveryDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryDeleteActionPerformed(evt);
            }
        });
        add(btnDeliveryDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, 40));

        btnDeliveryCreate.setBackground(new java.awt.Color(214, 50, 48));
        btnDeliveryCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliveryCreate.setText("Create");
        btnDeliveryCreate.setBorder(null);
        btnDeliveryCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryCreateActionPerformed(evt);
            }
        });
        add(btnDeliveryCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 170, 30));

        btnDeliveryBack.setBackground(new java.awt.Color(214, 50, 48));
        btnDeliveryBack.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliveryBack.setText("Back");
        btnDeliveryBack.setBorder(null);
        btnDeliveryBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryBackActionPerformed(evt);
            }
        });
        add(btnDeliveryBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, 40));

        tblDelivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "User Name", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblDelivery);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPasswordActionPerformed

    private void txtCustomerUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerUserNameActionPerformed

    private void btnDeliverySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliverySaveActionPerformed
        // TODO add your handling code here:
        if(txtCustomerName.getText().equals("") || txtCustomerUserName.getText().equals("") || txtCustomerPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter all fields");
        }else{
            ecosystem.getUserAccountDirectory().updateUserAccount(userAccount,txtCustomerName.getText(),txtCustomerUserName.getText(),txtCustomerPassword.getText(),null,null);
        displayDeliveryTable();
        txtCustomerName.setText("");
        txtCustomerUserName.setText("");
        txtCustomerPassword.setText("");
        } 
        
    }//GEN-LAST:event_btnDeliverySaveActionPerformed

    private void btnDeliveryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryUpdateActionPerformed
        // TODO add your handling code here:
        int focusRow = tblDelivery.getSelectedRow();

        if(focusRow >= 0){
            String name = (String) tblDelivery.getValueAt(focusRow, 0);
            String username= (String) tblDelivery.getValueAt(focusRow, 1);
            String password= (String) tblDelivery.getValueAt(focusRow, 2);
            userAccount = ecosystem.getUserAccountDirectory().authenticateUser(username, password);

            txtCustomerName.setText(name+"");
            txtCustomerUserName.setText(username+"");
            txtCustomerPassword.setText(password+"");

            JOptionPane.showMessageDialog(null,"Please press save button to save the Delivery Man information after updating the text field");

        }
        else {
            JOptionPane.showMessageDialog(null,"Please select a restaurant to update a Delivery Man profile");
        }
    }//GEN-LAST:event_btnDeliveryUpdateActionPerformed

    private void btnDeliveryDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryDeleteActionPerformed
        // TODO add your handling code here:
        int focusRow = tblDelivery.getSelectedRow();
        if(focusRow >= 0){
            int focusButton = JOptionPane.YES_NO_OPTION;
            int focusResult = JOptionPane.showConfirmDialog(null, "Confirm delete?","Warning",focusButton);
            if(focusResult == JOptionPane.YES_OPTION){
                String username= (String) tblDelivery.getValueAt(focusRow, 1);
                String password= (String) tblDelivery.getValueAt(focusRow, 2);
                UserAccount user=ecosystem.getUserAccountDirectory().authenticateUser(username, password);

                ecosystem.getUserAccountDirectory().deleteUserAccount(userAccount);
                ecosystem.getCustomerDirectory().deleteCustomer(userAccount.getUsername());
                displayDeliveryTable();
            }else{
                JOptionPane.showMessageDialog(null, "Please select a delivery man profile to delete the restaurant account");
            }
        }
    }//GEN-LAST:event_btnDeliveryDeleteActionPerformed

    private void btnDeliveryCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryCreateActionPerformed
        // TODO add your handling code here:
        if(txtCustomerName.getText().equals("") || txtCustomerUserName.getText().equals("") || txtCustomerPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please Enter all fields");
        }else{
            if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtCustomerUserName.getText())){
            UserAccount userAcc = ecosystem.getUserAccountDirectory().createUserAccount(txtCustomerName.getText(),txtCustomerUserName.getText(),txtCustomerPassword.getText(),null,null,null ,new DeliverManRole());
            DeliveryMan deliveryMan = ecosystem.getDeliveryManDirectory().createDeliveryMan(txtCustomerUserName.getText());
            displayDeliveryTable();
            System.out.println("1");
            txtCustomerName.setText("");
            txtCustomerUserName.setText("");
            txtCustomerPassword.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Delivery Man Username is not unique");
        }
        } 
        
    }//GEN-LAST:event_btnDeliveryCreateActionPerformed

    private void btnDeliveryBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryBackActionPerformed
        // TODO add your handling code here:
        userContainer.remove(this);
        CardLayout card = (CardLayout) userContainer.getLayout();
        card.previous(userContainer);
    }//GEN-LAST:event_btnDeliveryBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeliveryBack;
    private javax.swing.JButton btnDeliveryCreate;
    private javax.swing.JButton btnDeliveryDelete;
    private javax.swing.JButton btnDeliverySave;
    private javax.swing.JButton btnDeliveryUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerPassword;
    private javax.swing.JLabel lblCustomerUserName;
    private javax.swing.JTable tblDelivery;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPassword;
    private javax.swing.JTextField txtCustomerUserName;
    // End of variables declaration//GEN-END:variables
}
